#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_WebService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class MyDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFöretag(Företag instance);
    partial void UpdateFöretag(Företag instance);
    partial void DeleteFöretag(Företag instance);
    partial void InsertErbjudande(Erbjudande instance);
    partial void UpdateErbjudande(Erbjudande instance);
    partial void DeleteErbjudande(Erbjudande instance);
    #endregion
		
		public MyDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Företag> Företags
		{
			get
			{
				return this.GetTable<Företag>();
			}
		}
		
		public System.Data.Linq.Table<Erbjudande> Erbjudandes
		{
			get
			{
				return this.GetTable<Erbjudande>();
			}
		}
		
		public System.Data.Linq.Table<Lista> Listas
		{
			get
			{
				return this.GetTable<Lista>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Företag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Namn;
		
		private string _Adress;
		
		private string _Telefon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnNamnChanging(string value);
    partial void OnNamnChanged();
    partial void OnAdressChanging(string value);
    partial void OnAdressChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    #endregion
		
		public Företag()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", CanBeNull=false, IsPrimaryKey=true, IsDbGenerated=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Namn", CanBeNull=false)]
		public string Namn
		{
			get
			{
				return this._Namn;
			}
			set
			{
				if ((this._Namn != value))
				{
					this.OnNamnChanging(value);
					this.SendPropertyChanging();
					this._Namn = value;
					this.SendPropertyChanged("Namn");
					this.OnNamnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress", CanBeNull=false)]
		public string Adress
		{
			get
			{
				return this._Adress;
			}
			set
			{
				if ((this._Adress != value))
				{
					this.OnAdressChanging(value);
					this.SendPropertyChanging();
					this._Adress = value;
					this.SendPropertyChanged("Adress");
					this.OnAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", CanBeNull=false)]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Erbjudande : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Titel;
		
		private string _Beskrivning;
		
		private System.DateTime _Startdatum;
		
		private System.DateTime _Slutdatum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTitelChanging(string value);
    partial void OnTitelChanged();
    partial void OnBeskrivningChanging(string value);
    partial void OnBeskrivningChanged();
    partial void OnStartdatumChanging(System.DateTime value);
    partial void OnStartdatumChanged();
    partial void OnSlutdatumChanging(System.DateTime value);
    partial void OnSlutdatumChanged();
    #endregion
		
		public Erbjudande()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", CanBeNull=false, IsPrimaryKey=true, IsDbGenerated=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titel", CanBeNull=false)]
		public string Titel
		{
			get
			{
				return this._Titel;
			}
			set
			{
				if ((this._Titel != value))
				{
					this.OnTitelChanging(value);
					this.SendPropertyChanging();
					this._Titel = value;
					this.SendPropertyChanged("Titel");
					this.OnTitelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beskrivning", CanBeNull=false)]
		public string Beskrivning
		{
			get
			{
				return this._Beskrivning;
			}
			set
			{
				if ((this._Beskrivning != value))
				{
					this.OnBeskrivningChanging(value);
					this.SendPropertyChanging();
					this._Beskrivning = value;
					this.SendPropertyChanged("Beskrivning");
					this.OnBeskrivningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Startdatum")]
		public System.DateTime Startdatum
		{
			get
			{
				return this._Startdatum;
			}
			set
			{
				if ((this._Startdatum != value))
				{
					this.OnStartdatumChanging(value);
					this.SendPropertyChanging();
					this._Startdatum = value;
					this.SendPropertyChanged("Startdatum");
					this.OnStartdatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slutdatum")]
		public System.DateTime Slutdatum
		{
			get
			{
				return this._Slutdatum;
			}
			set
			{
				if ((this._Slutdatum != value))
				{
					this.OnSlutdatumChanging(value);
					this.SendPropertyChanging();
					this._Slutdatum = value;
					this.SendPropertyChanged("Slutdatum");
					this.OnSlutdatumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Lista
	{
		
		private string _FöretagID;
		
		private string _ErbjudandeID;
		
		public Lista()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FöretagID", CanBeNull=false)]
		public string FöretagID
		{
			get
			{
				return this._FöretagID;
			}
			set
			{
				if ((this._FöretagID != value))
				{
					this._FöretagID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErbjudandeID", CanBeNull=false)]
		public string ErbjudandeID
		{
			get
			{
				return this._ErbjudandeID;
			}
			set
			{
				if ((this._ErbjudandeID != value))
				{
					this._ErbjudandeID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
